export const TOP_FIFTY = {
    siteNames: [
        "Google",
        "Google.com",
        "Youtube",
        "Youtube.com",
        "Facebook",
        "Facebook.com",
        "Reddit",
        "Reddit.com",
        "Amazon",
        "Amazon.com",
        "Wikipedia",
        "Wikipedia.org",
        "Yahoo",
        "Yahoo.com",
        "Twitter",
        "Twitter.com",
        "Netflix",
        "Netflix.com",
        "Ebay",
        "Ebay.com",
        "image er",
        "Imgur",
        "Imgur.com",
        "Linkedin",
        "Linkedin.com",
        "Instagram",
        "Instagram.com",
        "Craigslist",
        "Craigslist.org",
        "en tee dee",
        "Ntd",
        "Ntd.tv",
        "dip lee",
        "Diply",
        "Diply.com",
        "Live",
        "Live.com",
        "Twitch",
        "Twitch.tv",
        "Tumblr",
        "Tumblr.com",
        "Microsoftonline",
        "Microsoftonline.com",
        "Office",
        "Office.com",
        "cee en en",
        "Cnn",
        "Cnn.com",
        "tee",
        "T",
        "T.co",
        "Pinterest",
        "Pinterest.com",
        "Pornhub",
        "Pornhub.com",
        "Bing",
        "Bing.com",
        "Livejasmin",
        "Livejasmin.com",
        "wiki ah",
        "Wikia",
        "Wikia.com",
        "Espn",
        "Espn.com",
        "eye em dee bee",
        "Imdb",
        "Imdb.com",
        "new york times",
        "Nytimes",
        "Nytimes.com",
        "Chase",
        "Chase.com",
        "Paypal",
        "Paypal.com",
        "Yelp",
        "Yelp.com",
        "Apple",
        "Apple.com",
        "Blogspot",
        "Blogspot.com",
        "Microsoft",
        "Microsoft.com",
        "Washingtonpost",
        "Washingtonpost.com",
        "Bankofamerica",
        "Bankofamerica.com",
        "ex videos",
        "Xvideos",
        "Xvideos.com",
        "Zillow",
        "Zillow.com",
        "Walmart",
        "Walmart.com",
        "Wordpress",
        "Wordpress.com",
        "em es en",
        "Msn",
        "Msn.com",
        "Wellsfargo",
        "Wellsfargo.com",
        "Weather",
        "Weather.com",
        "Salesforce",
        "Salesforce.com",
        "Github",
        "Github.com",
        "Buzzfeed",
        "Buzzfeed.com",
        "Stackoverflow",
        "Stackoverflow.com",
    ]
};